#!/bin/bash
# Script to configure ufw to block all incoming traffic except for SSH , HTTP, and HTTPS

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root. Use sudo to execute it."
   exit 1
fi

apt update -y && apt install ufw -y
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
ufw status verbose
