#!/usr/bin/env bash
# Installs and configures HAProxy on the load balancer

# Install required software
apt-get -y update
apt-get -y install haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

# Create new HAProxy configuration
cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6261-web-01 44.223.24.202:80 check
    server 6261-web-02 23.22.110.229:80 check
EOF

# Start HAProxy service
service haproxy restart
