#!/usr/bin/env bash
# Transfers a file from client to server using scp

args=("$@")

if [ "${#args[@]}" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning command-line arguments to variables
pathToFile="${args[0]}"
serverIP="${args[1]}"
username="${args[2]}"
pathToSSH="${args[3]}"

# Secure copy command for the file transfer
scp -o StrictHostKeyChecking=no -i "$pathToSSH" "$pathToFile" "$username@$serverIP:~/"
