#!/usr/bin/env bash
# Installs, configures, and starts the server

# Update package list and install Nginx
apt-get update
apt-get -y install nginx

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create the web root directory and set permissions
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

# Create a simple index.html file
echo 'Hello World!' > /var/www/html/index.html

# Configure Nginx redirection
SERVER_CONFIG=$(cat << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    if (\$request_filename ~ redirect_me/){
        rewrite ^ https://beap.vercel.app;
    }
}
EOF
)
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Start or restart Nginx
if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi
