#!/usr/bin/env bash
# sets up a new 404 error page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple index.html file
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# Create the custom 404.html file
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Configure Nginx
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me/ {
      return 301 https://beap.vercel.app;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
